services:
    frontend:
        container_name: frontend
        build: ./frontend
        restart: unless-stopped
        ports:
            - "80:80"
        networks:
            - network
        depends_on:
            - backend
        develop:
            watch:
                - path: ./frontend
                  action: rebuild

    backend:
        container_name: backend
        build: ./backend
        restart: unless-stopped
        networks:
            - network
            - network-db
        depends_on:
            - database
        env_file:
            - db.env
            - backend.env
        environment:
            DB_DSN: "pgsql:host=database;port=5432;dbname=database;user=postgres;password=postgres"
        develop:
            watch:
                - path: ./backend
                  ignore:
                      - src/**
                  action: rebuild
                - path: ./backend/src
                  target: /var/www/html
                  action: sync

    database:
        container_name: database
        image: postgres:18-alpine
        restart: unless-stopped
        ports:
            - 5434:5432
        volumes:
            - "./database/database.sql:/docker-entrypoint-initdb.d/database.sql"
        networks:
            - network-db
        env_file:
            - db.env
        develop:
            watch:
                - path: ./database
                  action: sync+restart
                  target: /docker-entrypoint-initdb.d

networks:
    network:
        driver: bridge
    network-db:
        driver: bridge
