ARG NODE_VERSION=24-alpine

FROM node:${NODE_VERSION} AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN --mount=type=cache,target=/root/.npm npm clean-install

COPY . .

EXPOSE 5173

CMD npm run dev