ARG NODE_VERSION=24-alpine

FROM node:${NODE_VERSION} AS builder

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./

RUN --mount=type=cache,target=/root/.npm npm clean-install

COPY frontend .

EXPOSE 5173

CMD npm run dev