user  nginx;
worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;

        location /index.php {
            include /etc/nginx/fastcgi_params;

            fastcgi_pass backend:9000;
            fastcgi_index index.php;

            fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        }

        location = / {
            rewrite ^(.*) /index.php last;
        }

        location / {
            rewrite ^/(.*)$ /index.php?controller=$1 last;
        }

        location ~^/api/(.*)/(.*)$ {
            rewrite ^/api/(.*)/(.*)$ /index.php?controller=$1&action=$2 last;
        }
    }
}
